name: CI

on: [push]

jobs:
  check_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - name: say hello
      run: echo "Hello!"
    
  check_windows:
    runs-on: windows-latest
    
    steps:
    - name: say hello
      run: echo "Hello!"
